"use strict";
/* =====================================================================
   DATA: the whole catalogue. Edit this file to add, change or remove entities.
   Row format: [id, category, name, description, "space separated related ids", {model,url,stage}]
   Relations are symmetric; declare each once on either side.
   Schema and editing rules: docs/data-model.md
   ===================================================================== */
const LAYERS = [
  {id:"source",     name:"Data Sources",            color:"#38bdf8", blurb:"Where open information originates: platforms, registries, sensors, ledgers and leaks."},
  {id:"provider",   name:"Data Providers",          color:"#f472b6", blurb:"Organizations that aggregate, enrich, sell or publish access to source data."},
  {id:"technique",  name:"Collection Techniques",   color:"#7bd389", blurb:"Methods used to discover, collect, exploit and verify information."},
  {id:"tool",       name:"Tools & Platforms",       color:"#fbbf24", blurb:"Software implementing collection, analysis, verification, preservation and OPSEC."},
  {id:"discipline", name:"Disciplines (INTs)",      color:"#b388ff", blurb:"Intelligence disciplines that OSINT contains, overlaps or feeds."},
  {id:"usecase",    name:"Use Cases & Sectors",     color:"#fb923c", blurb:"Who uses OSINT and for what."},
  {id:"governance", name:"Frameworks, Law & Ethics",color:"#a3b1c6", blurb:"Process models, standards, laws and ethical norms that shape practice."},
  {id:"community",  name:"Community & Training",    color:"#2dd4bf", blurb:"Organizations, training providers, directories and communities of practice."},
  {id:"trend",      name:"Trends & Challenges",     color:"#f87171", blurb:"Forces currently reshaping the ecosystem."}
];
const MODELS = {commercial:"Commercial", freemium:"Freemium", free:"Free", oss:"Open source", public:"Public sector"};
const STAGES = [
  {id:"plan",        name:"Planning & direction",          blurb:"Define requirements, scope, legal basis and risk before touching a source."},
  {id:"collect",     name:"Collection",                    blurb:"Gather data via search, APIs, scraping, feeds, sensors and requests."},
  {id:"process",     name:"Processing & exploitation",     blurb:"Make raw collection usable: extract, translate, transcribe, de-duplicate, resolve entities."},
  {id:"analyze",     name:"Analysis & production",         blurb:"Verify, correlate and interpret to produce judgments with stated confidence."},
  {id:"disseminate", name:"Dissemination & preservation",  blurb:"Report, share and preserve with provenance so findings are reproducible."}
];
const XCUT = {id:"opsec", name:"Cross-cutting: OPSEC, legal & ethics", blurb:"Applies at every stage: protect the investigator, respect the law and platform terms, minimize harm to subjects and bystanders."};

const C="commercial", F="freemium", FR="free", O="oss", P="public";
const m=(model,url,stage,notes)=>({model,url,stage,notes});
const st=(stage,notes)=>({stage,notes});

const RAW = {
source: [
 ["s_social","Online & social","Social media platforms","Public profiles, posts, comments, reactions, follower graphs and groups on platforms such as X, Facebook, Instagram, TikTok, LinkedIn, Reddit, VK and Weibo. The richest and most volatile OSINT source."],
 ["s_messaging","Online & social","Messaging apps & channels","Public Telegram channels and groups, Discord servers, WhatsApp communities and similar spaces; increasingly where breaking content and coordination appear first."],
 ["s_forums","Online & social","Forums, boards & alt-platforms","Niche forums, imageboards, alt-tech platforms and comment sections hosting subcultures, extremist content and early-stage narratives."],
 ["s_video","Online & social","Video & livestream platforms","YouTube, TikTok, Twitch, Rumble, Bilibili and others: footage, upload metadata, comments, captions and channel networks."],
 ["s_web","Web & content","Surface web & search indexes","Websites indexed by Google, Bing, Yandex, Baidu and others, including documents, cached pages and site structure."],
 ["s_archives","Web & content","Web archives","Historical page snapshots from the Wayback Machine, archive.today, Common Crawl and national web archives; key for deleted or changed content."],
 ["s_news","Web & content","News & broadcast media","Wire services, national and local outlets, press releases and broadcast transcripts; also the basis of adverse-media screening."],
 ["s_academic","Web & content","Academic, patents & grey literature","Journals, preprints, theses, patents, think-tank reports and conference papers revealing research, expertise and technology transfer."],
 ["s_images","Web & content","Images, video & file metadata","Photos, video and documents with embedded EXIF/XMP/office metadata, plus reverse-image indexes revealing reuse and origin."],
 ["s_events","Web & content","Event & conflict datasets","Structured, coded datasets of events, protests and conflict incidents (e.g. ACLED, GDELT) for trend and pattern analysis."],
 ["s_jobs","Web & content","Job postings & professional profiles","Vacancies and career profiles expose technology stacks, org structure, locations, clearances and expansion plans."],
 ["s_domains","Technical infrastructure","Domains, WHOIS & DNS","Registration records (largely redacted since GDPR), historical WHOIS, live and passive DNS, nameservers and hosting relationships."],
 ["s_certs","Technical infrastructure","Certificate transparency logs","Public append-only logs of issued TLS certificates exposing hostnames, subdomains and issuance timelines."],
 ["s_scan","Technical infrastructure","Internet-wide scan data","Banners, open ports, services, TLS fingerprints, exposed databases and IoT/ICS devices indexed by continuous scanning."],
 ["s_code","Technical infrastructure","Code repositories & paste sites","GitHub, GitLab, Bitbucket, Pastebin and similar: leaked secrets, configuration, commit identities and developer networks."],
 ["s_threat","Technical infrastructure","Threat & malware telemetry","Malware samples, sandbox reports, indicators of compromise, honeypot sightings and abuse feeds."],
 ["s_mobile","Technical infrastructure","Ad-tech & location data","Advertising IDs, bidstream and SDK-harvested device-location data traded by brokers; legally and ethically contested."],
 ["s_apis","Applications & APIs","Web & mobile app APIs","JSON, GraphQL, gRPC and WebSocket backends behind websites and apps. Often richer than the rendered page: internal IDs, precise timestamps, geodata, counters and fields the UI never displays."],
 ["s_clientcode","Applications & APIs","App packages & client code","Android APKs, iOS IPAs, JavaScript bundles, source maps and WebAssembly. They embed API hosts, endpoints, keys, feature flags, SDK inventories and signing certificates."],
 ["s_corp","Records & registries","Corporate registries","Incorporations, officers, shareholders, addresses and filings from national and state company registries."],
 ["s_beneficial","Records & registries","Beneficial ownership & leak archives","Ultimate-beneficial-owner registers and structured leak datasets (Panama, Paradise, Pandora Papers) exposing hidden ownership."],
 ["s_courts","Records & registries","Court & legal records","Dockets, judgments, bankruptcies, liens and enforcement actions from court portals and gazettes."],
 ["s_gov","Records & registries","Government & public records","Procurement notices, budgets, land and property registries, lobbying and asset declarations, gazettes and FOI releases."],
 ["s_sanctions","Records & registries","Sanctions, PEP & watchlists","OFAC, EU, UN and UK sanctions lists, export-control lists, politically exposed persons and law-enforcement notices."],
 ["s_finance","Finance & trade","Financial filings & markets","Securities filings, annual reports, ratings, funding rounds and public market data."],
 ["s_trade","Finance & trade","Trade & customs data","Bills of lading, import/export manifests and HS-coded shipment records used for supply-chain and sanctions-evasion analysis."],
 ["s_blockchain","Finance & trade","Blockchain ledgers","Public transaction histories on Bitcoin, Ethereum and other chains: addresses, smart contracts and token flows."],
 ["s_imagery","Geospatial & movement","Satellite & aerial imagery","Optical, multispectral and synthetic-aperture radar (SAR) imagery from commercial and public constellations, plus aerial and drone imagery."],
 ["s_maps","Geospatial & movement","Maps & street-level imagery","OpenStreetMap, Google/Apple/Bing/Yandex maps, Street View, Mapillary and user-contributed points of interest and photos."],
 ["s_ais","Geospatial & movement","Maritime AIS","Automatic Identification System broadcasts giving vessel identity, position, course and declared destination."],
 ["s_adsb","Geospatial & movement","Aviation ADS-B / Mode-S","Aircraft position and identity broadcasts collected by crowd-sourced receiver networks, plus aircraft registries."],
 ["s_rf","Geospatial & movement","Open radio & signals","Public radio scanners, WebSDRs, HF/VHF amateur and utility transmissions that anyone can lawfully receive (rules vary by country)."],
 ["s_sensor","Geospatial & movement","Environmental & remote sensing","Thermal-anomaly/fire detection, seismic, weather, night-time lights and air-quality data."],
 ["s_people","Identity & people","People-search & data brokers","Aggregated addresses, phone numbers, emails, relatives and associates; coverage and legality vary sharply by jurisdiction."],
 ["s_phone","Identity & people","Phone & email identifiers","Carrier and line-type lookups, crowd-sourced caller ID, and account-registration signals tied to emails and numbers."],
 ["s_breach","Underground & leaks","Breach & leak data","Leaked databases, credential dumps, combolists and infostealer logs. High value, with strict legal and ethical constraints."],
 ["s_darkweb","Underground & leaks","Dark web & underground markets","Tor/I2P services, criminal marketplaces and forums, ransomware leak sites and closed cybercrime communities."]
],
provider: [
 ["p_rf","Threat & cyber intelligence","Recorded Future","Threat-intelligence platform fusing open web, dark web, technical and adversary-infrastructure sources; acquired by Mastercard (2024).","s_threat s_darkweb s_domains s_news s_scan",m(C,"https://www.recordedfuture.com")],
 ["p_flashpoint","Threat & cyber intelligence","Flashpoint","Intelligence on illicit online communities, ransomware, fraud and physical-security threats; absorbed social-media OSINT vendor Echosec.","s_darkweb s_forums s_messaging s_breach s_social",m(C,"https://flashpoint.io")],
 ["p_intel471","Threat & cyber intelligence","Intel 471","Cybercrime intelligence on underground actors, forums and malware families.","s_darkweb s_forums s_threat s_messaging",m(C,"https://intel471.com")],
 ["p_vt","Threat & cyber intelligence","VirusTotal","Google-owned multi-engine file and URL scanning with passive DNS, relationship graphs and retro-hunting; free web tier, paid enterprise.","s_threat s_domains",m(F,"https://www.virustotal.com")],
 ["p_greynoise","Threat & cyber intelligence","GreyNoise","Classifies internet-wide scanning and background noise so analysts can separate opportunistic from targeted activity.","s_scan s_threat",m(F,"https://www.greynoise.io")],
 ["p_otx","Threat & cyber intelligence","AlienVault OTX","Free community threat exchange of ‘pulses’ containing indicators and context.","s_threat",m(FR,"https://otx.alienvault.com")],
 ["p_urlscan","Threat & cyber intelligence","urlscan.io","Sandbox that visits URLs and records screenshots, DOM, requests and certificates, with a searchable scan history.","s_web s_domains s_threat",m(F,"https://urlscan.io")],
 ["p_abusech","Threat & cyber intelligence","abuse.ch","Community projects (MalwareBazaar, URLhaus, ThreatFox) sharing malware samples and IOCs.","s_threat",m(FR,"https://abuse.ch")],
 ["p_msti","Threat & cyber intelligence","Threat intelligence in Microsoft Defender","Internet-infrastructure and passive-DNS datasets inherited from the 2021 RiskIQ acquisition; the standalone Defender Threat Intelligence (Defender TI) portal retired 1 Aug 2026, with its data folded into Microsoft Defender XDR and Sentinel.","s_domains s_scan s_threat s_certs",m(C)],
 ["p_shodan","Internet infrastructure","Shodan","Search engine for internet-connected devices, banners, vulnerabilities and ICS; query by port, product, org or favicon hash.","s_scan",m(F,"https://www.shodan.io")],
 ["p_censys","Internet infrastructure","Censys","Internet-wide scan and certificate datasets with attack-surface management.","s_scan s_certs",m(F,"https://censys.com")],
 ["p_fofa","Internet infrastructure","FOFA / ZoomEye","China-based internet asset search engines with strong Asia coverage and distinctive fingerprints.","s_scan",m(F)],
 ["p_domaintools","Internet infrastructure","DomainTools","WHOIS history, domain risk scoring, Iris investigations and Farsight DNSDB passive DNS.","s_domains",m(C,"https://www.domaintools.com")],
 ["p_strails","Internet infrastructure","SecurityTrails","Historical DNS, WHOIS and subdomain data with API access.","s_domains",m(F,"https://securitytrails.com")],
 ["p_whoisxml","Internet infrastructure","WhoisXML API","API and bulk access to WHOIS, DNS, IP, reverse-WHOIS and newly-registered-domain feeds.","s_domains",m(C,"https://whoisxmlapi.com")],
 ["p_crtsh","Internet infrastructure","crt.sh","Free search interface over certificate transparency logs.","s_certs",m(FR,"https://crt.sh")],
 ["p_builtwith","Internet infrastructure","BuiltWith","Profiles website technologies and historical analytics/ad tracker IDs; useful for linking sites to a common operator.","s_web",m(F,"https://builtwith.com")],
 ["p_hunter","Internet infrastructure","Hunter.io","Finds and verifies professional email addresses and naming patterns for a domain.","s_web s_phone",m(F,"https://hunter.io")],
 ["p_google","Search & image","Google Search & Lens","Largest web index with advanced operators, plus Lens visual search for objects, places and text.","s_web s_images",m(FR,"https://www.google.com")],
 ["p_yandex","Search & image","Yandex Search & Images","Strong reverse-image and similarity matching and deep Russian-language web coverage.","s_web s_images",m(FR,"https://yandex.com/images")],
 ["p_tineye","Search & image","TinEye","Reverse-image search for exact and modified copies with first-seen dates.","s_images",m(F,"https://tineye.com")],
 ["p_pimeyes","Search & image","PimEyes","Public face-search engine across the open web; controversial and restricted under some privacy regimes.","s_images",m(C,"https://pimeyes.com")],
 ["p_clearview","Search & image","Clearview AI","Facial-recognition database built from scraped images and sold to law enforcement; fined by several European data-protection authorities.","s_images s_social",m(C)],
 ["p_dataminr","Social & media monitoring","Dataminr","AI-driven real-time event and risk alerting from public data streams.","s_social s_news s_events",m(C,"https://www.dataminr.com")],
 ["p_meltwater","Social & media monitoring","Meltwater","Media monitoring and social listening across news, broadcast and social.","s_news s_social s_video",m(C,"https://www.meltwater.com")],
 ["p_brandwatch","Social & media monitoring","Brandwatch","Consumer and social intelligence with large historical social datasets.","s_social s_forums",m(C,"https://www.brandwatch.com")],
 ["p_zignal","Social & media monitoring","Zignal Labs","Narrative and media intelligence for communications and security teams.","s_social s_news",m(C)],
 ["p_graphika","Social & media monitoring","Graphika","Network mapping of online communities to detect influence operations and coordinated behavior.","s_social s_forums",m(C,"https://graphika.com")],
 ["p_blackbird","Social & media monitoring","Blackbird.AI","Narrative-risk intelligence detecting manipulation and harmful narratives.","s_social s_news",m(C)],
 ["p_metacl","Social & media monitoring","Meta Content Library","Application-based researcher access to public Facebook/Instagram content; successor to CrowdTangle, shut down in August 2024.","s_social",m(FR)],
 ["p_xapi","Social & media monitoring","X API","Programmatic access to X (Twitter) data; moved to paid tiers in 2023, ending broad free academic access.","s_social",m(C)],
 ["p_tgstat","Social & media monitoring","TGStat","Catalog, search and analytics for Telegram channels and chats.","s_messaging",m(F,"https://tgstat.com")],
 ["p_pipl","Identity & breach","Pipl","Identity resolution linking emails, phones, usernames and social profiles for investigations and fraud teams.","s_people s_social s_phone",m(C,"https://pipl.com")],
 ["p_sociallinks","Identity & breach","Social Links","SOCMINT platform and data provider, also delivered as Maltego transforms.","s_social s_messaging s_people",m(C,"https://sociallinks.io")],
 ["p_shadowdragon","Identity & breach","ShadowDragon","Social-media and online-identity collection tools (SocialNet, Horizon) for investigators.","s_social s_forums s_breach",m(C,"https://shadowdragon.io")],
 ["p_babel","Identity & breach","Babel Street","Multilingual publicly-available-information analytics and identity matching for government and enterprise.","s_social s_news s_mobile",m(C)],
 ["p_spycloud","Identity & breach","SpyCloud","Recaptured breach, malware and infostealer data for account-takeover prevention and investigations.","s_breach",m(C,"https://spycloud.com")],
 ["p_constella","Identity & breach","Constella Intelligence","Identity-exposure data from breach and public sources for digital-risk protection.","s_breach s_social",m(C)],
 ["p_hibp","Identity & breach","Have I Been Pwned","Breach-notification service by email and domain; widely used reference for whether a breach included an account.","s_breach",m(F,"https://haveibeenpwned.com")],
 ["p_dehashed","Identity & breach","DeHashed","Searchable breach-data engine for emails, usernames, names, IPs and more.","s_breach",m(C,"https://dehashed.com")],
 ["p_intelx","Identity & breach","Intelligence X","Search engine and archive for leaks, darknet, paste sites and historical web content.","s_breach s_darkweb s_code s_archives",m(F,"https://intelx.io")],
 ["p_epieos","Identity & breach","Epieos","Reverse email and phone lookup revealing linked accounts and public profile data.","s_phone s_social",m(F,"https://epieos.com")],
 ["p_lexis","Identity & breach","LexisNexis Risk / Accurint","US-centric public-records aggregation for permissible-purpose investigations.","s_people s_gov s_courts",m(C)],
 ["p_tlo","Identity & breach","TransUnion TLOxp","US investigative people and asset data restricted to vetted, permissible-purpose users.","s_people s_phone",m(C)],
 ["p_orbis","Corporate, risk & compliance","Moody's Orbis","Global company database (Bureau van Dijk) with ownership structures, financials and corporate hierarchies.","s_corp s_beneficial s_finance",m(C)],
 ["p_dj","Corporate, risk & compliance","Dow Jones Risk & Compliance","Sanctions, PEP, adverse-media and state-ownership screening data.","s_sanctions s_news",m(C)],
 ["p_worldcheck","Corporate, risk & compliance","LSEG World-Check","PEP and heightened-risk individual and entity screening database.","s_sanctions s_news",m(C)],
 ["p_sayari","Corporate, risk & compliance","Sayari","Global corporate-ownership and trade network graph for sanctions, supply-chain and fraud investigations.","s_corp s_trade s_beneficial",m(C,"https://sayari.com")],
 ["p_kharon","Corporate, risk & compliance","Kharon","Sanctions, export-control and forced-labor risk analytics across corporate networks.","s_sanctions s_corp s_trade",m(C)],
 ["p_opencorp","Corporate, risk & compliance","OpenCorporates","Large open database of companies aggregated from official registries worldwide.","s_corp",m(F,"https://opencorporates.com")],
 ["p_opensanctions","Corporate, risk & compliance","OpenSanctions","Open, consolidated dataset of sanctions targets, PEPs and entities of interest.","s_sanctions",m(F,"https://www.opensanctions.org")],
 ["p_aleph","Corporate, risk & compliance","OCCRP Aleph","Investigative data platform of leaked documents, registries and datasets for journalists.","s_beneficial s_corp s_gov s_courts",m(FR,"https://aleph.occrp.org")],
 ["p_icij","Corporate, risk & compliance","ICIJ Offshore Leaks","Searchable entities and relationships from the Panama, Paradise and Pandora Papers and other leaks.","s_beneficial",m(FR,"https://offshoreleaks.icij.org")],
 ["p_panjiva","Corporate, risk & compliance","Panjiva / ImportGenius","Customs and bill-of-lading data for mapping shippers, consignees and supply chains.","s_trade",m(C)],
 ["p_crunchbase","Corporate, risk & compliance","Crunchbase","Startup, investor, funding and executive data.","s_finance s_corp",m(F,"https://www.crunchbase.com")],
 ["p_gleif","Corporate, risk & compliance","GLEIF","Global Legal Entity Identifier index with parent/child relationships.","s_corp",m(FR,"https://www.gleif.org")],
 ["p_edgar","Corporate, risk & compliance","SEC EDGAR","Free US securities filings: annual reports, ownership forms and insider transactions.","s_finance s_corp",m(P,"https://www.sec.gov/search-filings")],
 ["p_ch","Corporate, risk & compliance","UK Companies House","Free UK company filings, officers and persons with significant control.","s_corp s_beneficial",m(P)],
 ["p_janes","Strategic & defense","Janes","Defense and security intelligence: equipment, order of battle and military installations.","s_imagery s_news s_academic",m(C,"https://www.janes.com")],
 ["p_strider","Strategic & defense","Strider Technologies","Strategic intelligence on state-directed talent, technology and supply-chain threats.","s_corp s_academic s_trade",m(C)],
 ["p_planet","Geospatial & tracking","Planet","Near-daily medium-resolution global imagery (PlanetScope) plus high-resolution tasking.","s_imagery",m(C,"https://www.planet.com")],
 ["p_maxar","Geospatial & tracking","Vantor","Very-high-resolution optical satellite imagery and 3D products widely used in conflict reporting; rebranded from Maxar (Maxar Intelligence) to Vantor in Oct 2025 after Advent International's 2023 take-private and split.","s_imagery",m(C)],
 ["p_airbus","Geospatial & tracking","Airbus OneAtlas","Pléiades, Pléiades Neo and SPOT imagery via a cloud platform.","s_imagery",m(C)],
 ["p_sar","Geospatial & tracking","ICEYE / Capella Space","Commercial SAR constellations that image through cloud and at night.","s_imagery",m(C)],
 ["p_copernicus","Geospatial & tracking","Copernicus (EU/ESA)","Free Sentinel-1 radar, Sentinel-2 optical and other open Earth-observation data.","s_imagery s_sensor",m(P,"https://dataspace.copernicus.eu")],
 ["p_nasa","Geospatial & tracking","NASA Earthdata (Landsat, FIRMS)","Free Landsat archives, VIIRS night lights and FIRMS active-fire detections.","s_imagery s_sensor",m(P,"https://earthdata.nasa.gov")],
 ["p_gearth","Geospatial & tracking","Google Earth & Maps","Global basemaps, historical imagery, 3D terrain and Street View.","s_maps s_imagery",m(FR,"https://earth.google.com")],
 ["p_osm","Geospatial & tracking","OpenStreetMap","Crowd-sourced open map of the world, queryable via Overpass.","s_maps",m(FR,"https://www.openstreetmap.org")],
 ["p_mt","Geospatial & tracking","MarineTraffic / VesselFinder","Terrestrial and satellite AIS vessel tracking with port calls and voyage history.","s_ais",m(F)],
 ["p_windward","Geospatial & tracking","Windward","Maritime AI for sanctions, dark activity and ship-to-ship transfer risk.","s_ais s_imagery",m(C)],
 ["p_fr24","Geospatial & tracking","Flightradar24","Global flight tracking from a large ADS-B/MLAT receiver network.","s_adsb",m(F,"https://www.flightradar24.com")],
 ["p_adsbx","Geospatial & tracking","ADS-B Exchange","Flight tracking historically known for not filtering blocked aircraft; community alternatives (adsb.lol, airplanes.live) grew after its 2023 sale.","s_adsb",m(F,"https://www.adsbexchange.com")],
 ["p_chainalysis","Blockchain analytics","Chainalysis","Blockchain analytics for tracing funds and attributing addresses for law enforcement and compliance.","s_blockchain",m(C)],
 ["p_elliptic","Blockchain analytics","Elliptic","Crypto-asset risk screening and cross-chain investigations.","s_blockchain",m(C)],
 ["p_trm","Blockchain analytics","TRM Labs","Blockchain intelligence for fraud, sanctions and financial-crime investigations.","s_blockchain",m(C)],
 ["p_arkham","Blockchain analytics","Arkham","Entity-labeled blockchain explorer and analytics.","s_blockchain",m(F)],
 ["p_etherscan","Blockchain analytics","Block explorers (Etherscan etc.)","Free explorers exposing transactions, contracts and labeled addresses per chain.","s_blockchain",m(FR,"https://etherscan.io")],
 ["p_darkowl","Dark web","DarkOwl","Searchable darknet data collected from Tor, I2P and other networks.","s_darkweb s_breach",m(C)],
 ["p_slcyber","Dark web","Searchlight Cyber","Dark-web investigation and monitoring for law enforcement and enterprise.","s_darkweb",m(C)],
 ["p_kela","Dark web","KELA","Cybercrime intelligence from underground markets and forums.","s_darkweb s_breach",m(C)],
 ["p_flare","Dark web","Flare","Threat-exposure management covering stealer logs, leaks and illicit Telegram channels.","s_darkweb s_breach s_messaging",m(C,"https://flare.io")],
 ["p_ahmia","Dark web","Ahmia","Search engine indexing Tor onion services, with abuse-content filtering.","s_darkweb",m(FR,"https://ahmia.fi")],
 ["p_brightdata","Scraping infrastructure","Bright Data","Residential, mobile and datacenter proxy networks, unblocking browsers, scraper APIs and pre-collected datasets; won summary judgment against Meta over scraping logged-out public data (Jan 2024), while X's suit was largely dismissed (May 2024), partly revived on amendment and settled in 2025.","s_web s_social",m(C,"https://brightdata.com")],
 ["p_oxylabs","Scraping infrastructure","Oxylabs","Proxy networks and scraper APIs for search engines, e-commerce and general web targets.","s_web",m(C,"https://oxylabs.io")],
 ["p_zyte","Scraping infrastructure","Zyte","Company behind Scrapy (formerly Scrapinghub); its API handles rendering, ban management and extraction.","s_web",m(C,"https://www.zyte.com")],
 ["p_apify","Scraping infrastructure","Apify","Platform and marketplace of ready-made scrapers (‘Actors’) for social, maps and e-commerce sites, with scheduling and storage.","s_web s_social s_maps",m(F,"https://apify.com")],
 ["p_exodus","App intelligence","Exodus Privacy","Free analysis of Android apps listing embedded trackers and requested permissions; useful for SDK and data-flow attribution.","s_clientcode s_mobile",m(FR,"https://exodus-privacy.eu.org")],
 ["p_sensortower","App intelligence","Sensor Tower","App-market intelligence: downloads, revenue, publishers and SDK usage across app stores.","s_clientcode",m(C)],
 ["p_gdelt","Open & nonprofit data","GDELT Project","Free global database of news events, themes and tone across 100+ languages.","s_news s_events",m(FR,"https://www.gdeltproject.org")],
 ["p_acled","Open & nonprofit data","ACLED","Curated conflict and protest event data worldwide; registration and license terms apply.","s_events",m(F,"https://acleddata.com")],
 ["p_wayback","Open & nonprofit data","Internet Archive / Wayback Machine","Largest public web archive with on-demand page capture.","s_archives",m(FR,"https://web.archive.org")],
 ["p_cc","Open & nonprofit data","Common Crawl","Open petabyte-scale web crawl corpus.","s_archives s_web",m(FR,"https://commoncrawl.org")]
],
technique: [
 ["k_req","Analysis & tradecraft","Requirements & collection planning","Define intelligence requirements, scope sources, assess legal basis and risk before collecting.","g_cycle g_ethics",st("plan")],
 ["k_dorking","Search & discovery","Advanced search operators (dorking)","Precise queries with site:, filetype:, inurl:, intitle:, date ranges and quoted phrases across multiple engines.","s_web s_code s_gov s_academic s_jobs p_google",st("collect")],
 ["k_archive","Search & discovery","Archive & cache retrieval","Recovering deleted or changed pages, profiles and documents from archives and caches.","s_archives s_web s_social p_wayback",st("collect")],
 ["k_foia","Search & discovery","FOI & public-records requests","Requesting documents from authorities under freedom-of-information laws.","s_gov s_courts",st("collect")],
 ["k_pdns","Technical reconnaissance","Passive DNS & WHOIS pivoting","Pivoting on historical resolutions, shared registrants, name servers and IPs to map infrastructure.","s_domains s_threat p_domaintools p_strails p_vt p_msti",st("collect")],
 ["k_ct","Technical reconnaissance","Certificate transparency mining","Enumerating hostnames and spotting look-alike phishing domains from CT log entries.","s_certs s_domains p_crtsh p_censys",st("collect")],
 ["k_scan","Technical reconnaissance","Scan-data querying & fingerprinting","Finding related servers by banner, favicon hash, JARM/JA4, certificate or HTML similarity.","s_scan s_threat p_shodan p_censys p_fofa",st("collect")],
 ["k_tracker","Technical reconnaissance","Tracker & analytics ID pivoting","Linking websites through shared Google Analytics, AdSense, Tag Manager or pixel IDs.","s_web s_domains p_builtwith",st("analyze")],
 ["k_subdomain","Technical reconnaissance","Subdomain & attack-surface enumeration","Discovering an organization's internet-facing assets from passive and active sources.","s_domains s_certs s_scan p_strails",st("collect")],
 ["k_username","Identity & social","Username enumeration","Checking handle reuse across platforms to link accounts to a single persona.","s_social s_forums s_code s_breach",st("collect")],
 ["k_email","Identity & social","Email & phone pivoting","Registration checks, breach lookups, avatar hashes and reverse lookups from an email address or phone number.","s_phone s_breach s_people s_social p_hibp p_epieos p_hunter",st("collect")],
 ["k_sockpuppet","Identity & social","Sock puppets & managed attribution","Maintaining research personas to view gated content without exposing the investigator; raises terms-of-service, legal and ethical questions.","s_social s_messaging s_forums s_darkweb",st("opsec")],
 ["k_socialmon","Identity & social","Social media monitoring & listening","Keyword, hashtag, account and geofence-based streams for situational awareness.","s_social s_video s_messaging s_news p_dataminr p_meltwater p_brandwatch",st("collect")],
 ["k_network","Identity & social","Social network analysis","Mapping follower and interaction graphs to find key nodes, communities and coordinated behavior.","s_social s_messaging s_forums p_graphika",st("analyze")],
 ["k_reverseimg","Image, video & geo","Reverse image & face search","Locating earlier copies, original sources or matching faces across multiple engines.","s_images s_social s_web p_google p_yandex p_tineye p_pimeyes",st("process")],
 ["k_metadata","Image, video & geo","Metadata analysis","Extracting EXIF, GPS, device, author and timestamp data from files (often stripped by platforms on upload).","s_images s_code s_gov",st("process")],
 ["k_geoloc","Image, video & geo","Geolocation","Matching terrain, buildings, signage, vegetation and infrastructure in imagery to maps and satellite views.","s_maps s_imagery s_images s_video p_gearth",st("analyze")],
 ["k_chrono","Image, video & geo","Chronolocation","Establishing when content was captured using shadows, sun angle, weather records and metadata.","s_images s_sensor s_video",st("analyze")],
 ["k_verify","Image, video & geo","Verification & provenance","Tracing first upload, checking context and manipulation, detecting synthetic media and reading content credentials.","s_images s_video s_social s_news",st("analyze")],
 ["k_imint","Movement & physical","Satellite imagery analysis","Change detection, object identification and SAR interpretation across time series.","s_imagery s_sensor p_planet p_maxar p_copernicus",st("analyze")],
 ["k_tracking","Movement & physical","Vessel & aircraft tracking","Monitoring AIS/ADS-B for routes, loitering, transponder gaps, spoofing and ship-to-ship transfers.","s_ais s_adsb s_imagery p_mt p_fr24 p_adsbx p_windward",st("collect")],
 ["k_rf","Movement & physical","SDR & open-signals monitoring","Receiving ADS-B, AIS and open radio with software-defined radios.","s_rf s_adsb s_ais",st("collect")],
 ["k_adtech","Movement & physical","Ad-tech & location-data analysis","Analyzing commercially sold device-location and bidstream data (ADINT); legally contested and increasingly regulated.","s_mobile",st("collect")],
 ["k_corp","Money & ownership","Corporate & ownership tracing","Following officers, shareholders, registered agents and addresses through shell structures to beneficial owners.","s_corp s_beneficial s_courts s_finance p_opencorp p_orbis p_sayari p_icij",st("analyze")],
 ["k_money","Money & ownership","Trade & financial-flow tracing","Using customs, procurement and filings to follow goods and money, including sanctions evasion.","s_trade s_finance s_gov s_sanctions p_panjiva p_kharon",st("analyze")],
 ["k_crypto","Money & ownership","Blockchain tracing","Clustering addresses and following funds through mixers, bridges and exchanges to attribute wallets.","s_blockchain s_darkweb p_chainalysis p_elliptic p_trm p_arkham p_etherscan",st("analyze")],
 ["k_darkweb","Underground","Dark-web & underground monitoring","Crawling and monitoring markets, forums, leak sites and illicit channels for mentions and actors.","s_darkweb s_forums s_messaging s_breach p_darkowl p_kela p_flare p_ahmia",st("collect")],
 ["k_breach","Underground","Breach & stealer-log analysis","Linking identities and infrastructure through leaked records; legality depends on jurisdiction and purpose.","s_breach s_darkweb p_spycloud p_dehashed p_intelx",st("process")],
 ["k_scraping","Collection engineering","Web crawling & HTML scraping","Automated, repeatable collection from rendered pages with crawlers and headless browsers. The most brittle rung of the access ladder: markup changes silently break parsers.","s_web s_social s_forums s_messaging",st("collect",[
   "Look for a structured source first: an official API, RSS, sitemap, embedded JSON (JSON-LD, framework hydration state) or a hidden API usually beats parsing HTML.",
   "Headless browsers handle JavaScript-heavy sites but are slower, costlier and easier to fingerprint than plain HTTP clients.",
   "Store raw responses next to parsed output so you can re-parse after layout changes and prove what was collected.",
   "Legal exposure is generally lowest for logged-out public pages and rises with login walls, accepted terms, personal data and volume."])],
 ["k_apidisc","Collection engineering","Hidden API discovery (web)","Watching a site's own network traffic to find the XHR/fetch, GraphQL or WebSocket endpoints that feed the page, then calling them directly for structured, paginated data.","s_apis s_web s_social k_scraping g_cfaa",st("collect",[
   "Workflow: open DevTools → Network (Fetch/XHR), perform the action in the UI, find the request that returns the data, copy it as cURL, then strip headers and parameters until it stops working to learn what is actually required.",
   "Look for pagination cursors, page-size limits and undocumented filters; responses frequently carry fields the UI hides.",
   "Export a HAR file as a reproducible record of what the site served.",
   "Hidden endpoints change without notice: monitor for schema drift instead of silently collecting nulls.",
   "Calling the same unauthenticated endpoint a browser calls is usually treated like viewing the page; rate, terms of service and personal-data law still apply."])],
 ["k_jsanalysis","Collection engineering","Client-code & source-map analysis","Reading JavaScript bundles, exposed source maps and config objects to enumerate endpoints, API hosts, environment names, feature flags and embedded keys without calling any of them.","s_clientcode s_apis s_code d_cti",st("collect",[
   "Search bundles for URL paths, api/graphql/v1-style routes, host names and environment names (staging, dev, internal).",
   "Published source maps (.map files) can reconstruct original source, including comments and route definitions.",
   "Embedded keys (maps, analytics, Firebase-style configs) identify the backing project and can link sites and apps to one operator.",
   "Passive by nature: reading code the server already sent you generates no extra traffic."])],
 ["k_graphql","Collection engineering","GraphQL introspection & schema mapping","Using introspection (when enabled), field-suggestion errors and queries observed in the client to map a GraphQL schema, then composing queries that return exactly the fields needed.","s_apis k_apidisc",st("collect",[
   "Introspection exposes every type, field and argument, including ones the official client never requests.",
   "With introspection disabled, error-message field suggestions and queries captured from the client can still reconstruct much of the schema.",
   "Many large platforms use persisted queries (hashed query IDs); collection then means replaying captured IDs with new variables.",
   "Fields that expose other users' private data are a disclosure issue, not a collection opportunity."])],
 ["k_mobilere","Collection engineering","Mobile app reverse engineering","Static analysis of APK/IPA packages (decompilation, string and resource extraction, manifest and SDK review) to find API hosts, endpoints, auth schemes and embedded secrets.","s_clientcode s_apis s_mobile g_dmca g_mastg",st("collect",[
   "Android apps decompile to fairly readable Java/Kotlin; iOS apps are native code needing a disassembler, and App Store builds are encrypted until decrypted on a jailbroken device.",
   "Start with the manifest or Info.plist, network-security config, string resources and the list of bundled SDKs: they often reveal hosts and third-party data flows within minutes.",
   "Obfuscation (R8/ProGuard, commercial protectors) renames symbols but rarely hides URLs or protocol structure.",
   "Mobile APIs are often older, less hardened and more generous than their web equivalents because the client is assumed to be trusted.",
   "EULAs typically prohibit reverse engineering; anti-circumvention and decompilation rules vary by jurisdiction."])],
 ["k_mitm","Collection engineering","Traffic interception & pinning bypass","Routing a test device's traffic through an intercepting proxy with a trusted CA to observe app requests; certificate pinning and root/jailbreak detection are defeated with runtime instrumentation.","s_apis k_mobilere g_dmca g_mastg",st("collect",[
   "Use a dedicated test device or emulator and a throwaway account, never personal devices or credentials.",
   "Since Android 7, apps ignore user-installed CAs unless they opt in, so interception usually needs a rooted device or emulator (system CA) or a repackaged app.",
   "Pinning, root detection and anti-debugging are common; instrumentation hooks those checks at runtime instead of modifying the package.",
   "Not everything is HTTP/JSON: expect WebSockets, gRPC/protobuf, MQTT and custom binary protocols that need schema recovery.",
   "Bypassing pinning or integrity checks can count as circumventing a technological protection measure; get legal sign-off first."])],
 ["k_apireplay","Collection engineering","Request signing & session replication","Reproducing what the official client does to call a private API outside the app: login and token-refresh flows, HMAC request signatures, device identifiers and integrity tokens.","s_apis k_mitm k_mobilere g_cfaa g_dmca",st("collect",[
   "Signatures usually combine path, body, timestamp and a key derived from the app; the signing routine is typically located by hooking crypto/HMAC calls at runtime.",
   "Device attestation (Play Integrity, App Attest) is built to be unforgeable off genuine devices; where enforced, collection shifts to automating the real app on real hardware.",
   "Authenticated private APIs tie every request to an account: expect rate limits, behavioral scoring and bans, and protect the research persona accordingly.",
   "The highest-risk rung of routine collection: you are using an interface the operator restricts to its own client, usually under terms you accepted."])],
 ["k_privateclients","Collection engineering","Unofficial clients & private-API libraries","Community libraries and downloaders that wrap a platform's private or internal API, so investigators can collect without doing the reverse engineering themselves.","s_apis s_social s_video k_apireplay",st("collect",[
   "They break whenever the platform changes its client; pin versions and check the issue tracker before relying on one mid-investigation.",
   "Most need logged-in sessions or exported cookies, which attaches all collection to an account.",
   "Review what the library sends and stores: some keep credentials or session cookies in plain text."])],
 ["k_apienum","Collection engineering","API endpoint & parameter discovery (active)","Probing hosts for undocumented routes, versions and parameters with wordlists and API-aware fuzzers, and looking for OpenAPI/Swagger documents left exposed.","s_apis s_scan k_subdomain g_cfaa u_redteam",st("collect",[
   "Exhaust passive sources first: exposed OpenAPI/Swagger files, archived API docs, JS bundles and app packages often enumerate routes without a single probe.",
   "Older API versions next to newer ones, and staging hosts, frequently lack newer protections.",
   "Active fuzzing generates traffic the target can see and attribute; it is penetration-testing activity and needs authorization outside a scoped engagement."])],
 ["k_antibot","Collection engineering","Anti-bot evasion & fingerprint management","Managing request rate, IP reputation, TLS/HTTP2 and browser fingerprints, cookies and CAPTCHAs so automated collection is neither blocked nor fed decoy data.","k_scraping k_apidisc s_web t_vpn",st("collect",[
   "Defenses score many layers together: IP/ASN reputation, TLS (JA3/JA4) and HTTP/2 fingerprints, headless-browser tells, JavaScript challenges and behavior over time.",
   "A plain HTTP library is often rejected on its TLS fingerprint before headers are read; fingerprint-impersonating clients or real browsers fix that layer.",
   "Some defenses serve plausible fake data rather than blocking: validate samples against the live UI.",
   "Slow, cached, incremental collection is the cheapest evasion and the easiest to defend.",
   "Deliberately defeating access controls weakens a ‘public data’ position; residential proxy networks raise their own consent questions."])],
 ["k_apiexploit","Collection engineering","API authorization flaws (BOLA/IDOR, data overexposure)","APIs that return other users' records because object-level authorization is missing (guessable IDs) or because endpoints return whole records the UI filters. Several notorious datasets originated here; it is the line between OSINT and intrusion.","s_apis g_owaspapi g_cfaa g_disclosure",st("opsec",[
   "Typical signals: sequential or predictable IDs in paths, and responses carrying emails, phone numbers, locations or private flags the UI never shows.",
   "Noticing overexposure in responses you legitimately received is passive analysis; deliberately enumerating IDs to pull other users' records is unauthorized access in most jurisdictions.",
   "Mass enumerations have been treated as breaches by regulators, e.g. the Irish DPC's €265m fine on Meta in 2022 over scraped user data.",
   "Right response for investigators: document minimally, stop, and report through coordinated disclosure."])],
 ["k_secrets","Collection engineering","Exposed keys & cloud misconfiguration","Finding API keys, tokens and cloud configs in apps, JavaScript, repos and pastes, and spotting openly readable storage (Firebase, S3 and similar) behind an app.","s_clientcode s_code s_apis k_jsanalysis g_cfaa g_disclosure d_cti",st("process",[
   "Keys are strong attribution pivots even when restricted: the same key across sites, apps and repos indicates a shared operator.",
   "Using a discovered key, or reading a misconfigured database to retrieve its contents, is access without authorization in most jurisdictions: record existence, not contents, and disclose.",
   "Secret scanners match known key formats and high-entropy strings; verify by context rather than by calling the API."])],
 ["k_appattrib","Collection engineering","App attribution pivoting","Linking apps to operators and to each other through signing certificates, developer accounts, package names, shared SDK keys, backend hosts and privacy-policy domains.","s_clientcode p_exodus p_sensortower k_entity k_jsanalysis u_brand",st("analyze",[
   "An Android signing-certificate fingerprint is stable across versions and often shared across an operator's apps, even under different developer names.",
   "Shared analytics, ad and push-notification keys link apps the same way tracker IDs link websites.",
   "Backend hosts found in the code feed straight into passive DNS and certificate pivots.",
   "APK mirror archives keep old versions that may expose endpoints or owners since removed."])],
 ["k_entity","Scale & automation","Entity resolution & link analysis","Merging records into entities and pivoting through relationships in a graph.","s_corp s_people s_social s_breach",st("process")],
 ["k_nlp","Scale & automation","Translation, NLP & transcription","Processing multilingual text, speech and video at scale: translation, named-entity recognition, topics and sentiment.","s_news s_video s_messaging s_social",st("process")],
 ["k_ai","Scale & automation","AI-assisted triage","LLMs, classifiers and embeddings to prioritize and summarize large collections; outputs need human verification.","s_news s_social s_images",st("process")],
 ["k_capture","Analysis & tradecraft","Evidence capture & preservation","Capturing content with hashes, timestamps and context so findings are reproducible and admissible.","s_web s_social s_video",st("disseminate")],
 ["k_opsec","Analysis & tradecraft","Investigator OPSEC","Isolating environments, managing attribution and avoiding tipping off subjects.","g_ethics",st("opsec")],
 ["k_sat","Analysis & tradecraft","Structured analytic techniques","Analysis of competing hypotheses, key-assumptions checks, devil's advocacy and source grading to reduce bias.","g_ach g_admiralty",st("analyze")],
 ["k_timeline","Analysis & tradecraft","Timeline & pattern-of-life analysis","Ordering events and recurring behaviors to establish sequence and routine.","s_social s_events s_images",st("analyze")],
 ["k_narrative","Analysis & tradecraft","Narrative & influence-operation analysis","Tracking narratives, amplification and coordinated inauthentic behavior across platforms.","s_social s_news s_messaging s_video p_zignal p_blackbird p_graphika",st("analyze")],
 ["k_report","Analysis & tradecraft","Reporting & visualization","Producing assessments with confidence language, sourcing, maps, charts and link diagrams.","g_admiralty",st("disseminate")]
],
tool: [
 ["t_maltego","Link analysis & case platforms","Maltego","Graph-based link-analysis platform that pivots between entities using transforms backed by a hub of data-provider integrations.","k_entity k_pdns k_username k_email k_corp p_sociallinks",m(C,"https://www.maltego.com","analyze")],
 ["t_i2","Link analysis & case platforms","i2 Analyst's Notebook","Long-standing link-charting and timeline tool in law-enforcement and intelligence analysis.","k_entity k_timeline",m(C,null,"analyze")],
 ["t_palantir","Link analysis & case platforms","Palantir Gotham","Data-integration and analysis platform for government and defense customers.","k_entity k_timeline",m(C,null,"analyze")],
 ["t_gephi","Link analysis & case platforms","Gephi","Open-source network visualization and community detection.","k_network",m(O,"https://gephi.org","analyze")],
 ["t_spiderfoot","Recon automation","SpiderFoot","Open-source OSINT automation with 200+ modules for IPs, domains, emails and names.","k_subdomain k_email k_scan k_breach",m(O,"https://github.com/smicallef/spiderfoot","collect")],
 ["t_reconng","Recon automation","Recon-ng","Modular reconnaissance framework with a Metasploit-like interface.","k_subdomain k_email",m(O,"https://github.com/lanmaster53/recon-ng","collect")],
 ["t_harvester","Recon automation","theHarvester","Gathers emails, names, subdomains and hosts from search engines and public APIs.","k_email k_subdomain",m(O,"https://github.com/laramies/theHarvester","collect")],
 ["t_amass","Recon automation","OWASP Amass","Attack-surface mapping and subdomain enumeration from passive and active sources.","k_subdomain k_ct k_pdns",m(O,"https://github.com/owasp-amass/amass","collect")],
 ["t_pd","Recon automation","ProjectDiscovery (subfinder, httpx)","Fast open-source recon utilities for passive subdomain discovery and probing.","k_subdomain k_scan",m(O,"https://github.com/projectdiscovery","collect")],
 ["t_sherlock","Identity enumeration","Sherlock / Maigret / WhatsMyName","Username enumeration across hundreds of sites; Maigret adds profile parsing, WhatsMyName maintains a shared site list.","k_username",m(O,"https://github.com/sherlock-project/sherlock","collect")],
 ["t_holehe","Identity enumeration","Holehe / GHunt","Check which services an email is registered with (Holehe) and investigate Google accounts (GHunt).","k_email",m(O,"https://github.com/megadose/holehe","collect")],
 ["t_phoneinfoga","Identity enumeration","PhoneInfoga","Phone-number reconnaissance: carrier, line type and search-engine footprinting.","k_email s_phone",m(O,"https://github.com/sundowndev/phoneinfoga","collect")],
 ["t_exif","Media forensics & verification","ExifTool","Reads and writes metadata in images, video, audio and documents.","k_metadata",m(O,"https://exiftool.org","process")],
 ["t_invid","Media forensics & verification","InVID-WeVerify plugin","Browser toolkit for video keyframes, reverse search, metadata and image forensics used by newsrooms.","k_verify k_reverseimg k_metadata",m(FR,null,"process")],
 ["t_forensically","Media forensics & verification","Forensically / FotoForensics","Image forensics: error-level analysis, clone detection and noise analysis.","k_verify",m(FR,null,"process")],
 ["t_suncalc","Geospatial","SunCalc","Computes sun position and shadow direction for any place and time; a core chronolocation aid.","k_chrono k_geoloc",m(FR,"https://www.suncalc.org","analyze")],
 ["t_peakvisor","Geospatial","PeakVisor","3D mountain-panorama matching to identify ridgelines in photos.","k_geoloc",m(F,"https://peakvisor.com","analyze")],
 ["t_overpass","Geospatial","Overpass Turbo","Queries OpenStreetMap features (e.g. a church near a river and a bridge) to shortlist geolocation candidates.","k_geoloc p_osm",m(FR,"https://overpass-turbo.eu","analyze")],
 ["t_qgis","Geospatial","QGIS","Open-source GIS for layering imagery, vector data and measurements.","k_geoloc k_imint",m(O,"https://qgis.org","analyze")],
 ["t_eobrowser","Geospatial","Copernicus Browser / EO Browser","Web viewers for searching and visualizing free Sentinel and Landsat imagery.","k_imint p_copernicus p_nasa",m(FR,null,"collect")],
 ["t_scrapy","Collection & scraping","Scrapy / Playwright / Selenium","Frameworks for crawling and headless-browser automation at scale.","k_scraping",m(O,"https://scrapy.org","collect")],
 ["t_telethon","Collection & scraping","Telethon / Telegram API clients","Python MTProto clients for collecting messages, media and metadata from public Telegram entities. Telethon's GitHub repository was archived in 2026; check that whichever client you use is still maintained before relying on it.","k_scraping s_messaging",m(O,"https://github.com/LonamiWebs/Telethon","collect")],
 ["t_4cat","Collection & scraping","4CAT","Research tool for capturing and analyzing datasets from forums and social platforms.","k_scraping k_network",m(O,null,"collect")],
 ["t_ytdlp","Collection & scraping","yt-dlp","Command-line downloader for video and audio from thousands of sites, preserving metadata; its per-site extractors track private player APIs.","k_capture k_privateclients s_video",m(O,"https://github.com/yt-dlp/yt-dlp","collect")],
 ["t_privlibs","Collection & scraping","instaloader / gallery-dl","Community clients for platform media and metadata built on private web and app APIs; typical of the private-API library genre.","k_privateclients s_social",m(O,null,"collect")],
 ["t_devtools","API & traffic analysis","Browser DevTools & HAR","Built-in network inspector for finding XHR/fetch, GraphQL and WebSocket calls, copying them as cURL and exporting HAR records.","k_apidisc k_jsanalysis",m(FR,null,"collect")],
 ["t_burp","API & traffic analysis","Burp Suite / Caido / OWASP ZAP","Intercepting proxies for inspecting, replaying and modifying web and app traffic.","k_mitm k_apidisc k_apienum",m(F,null,"collect")],
 ["t_mitmproxy","API & traffic analysis","mitmproxy / HTTP Toolkit","Scriptable open-source interception proxies; add-ons can log or transform every request an app makes.","k_mitm k_apidisc",m(O,"https://mitmproxy.org","collect")],
 ["t_postman","API & traffic analysis","Postman / Bruno / Insomnia","Clients for organizing, parameterizing and replaying discovered API requests as reusable collections.","k_apidisc k_apireplay",m(F,null,"collect")],
 ["t_graphql","API & traffic analysis","GraphQL tooling (InQL, Clairvoyance, Voyager)","Introspection, schema reconstruction when introspection is disabled, and schema visualization.","k_graphql",m(O,null,"collect")],
 ["t_apifuzz","API & traffic analysis","Kiterunner / ffuf / Arjun","Active route, content and parameter discovery against web servers and APIs; requires authorization.","k_apienum",m(O,null,"collect")],
 ["t_jadx","Mobile reverse engineering","jadx / apktool","Android decompilation to Java source, plus resource decoding and app repackaging.","k_mobilere k_appattrib",m(O,"https://github.com/skylot/jadx","process")],
 ["t_frida","Mobile reverse engineering","Frida / Objection","Dynamic instrumentation for hooking app functions at runtime: pinning and root-detection bypass, tracing crypto and request-signing routines.","k_mitm k_apireplay k_mobilere",m(O,"https://frida.re","collect")],
 ["t_ghidra","Mobile reverse engineering","Ghidra / radare2","Open-source disassemblers and decompilers for native code such as iOS binaries and Android native libraries (IDA Pro is the commercial alternative).","k_mobilere k_apireplay",m(O,"https://ghidra-sre.org","process")],
 ["t_mobsf","Mobile reverse engineering","MobSF","Automated static and dynamic analysis of Android and iOS apps: endpoints, secrets, trackers and permissions.","k_mobilere k_secrets",m(O,"https://github.com/MobSF/Mobile-Security-Framework-MobSF","process")],
 ["t_emu","Mobile reverse engineering","Emulators & test devices","Android emulators and rooted or jailbroken test phones (e.g. Android Studio AVD, Genymotion, Magisk) that keep app analysis off personal devices.","k_mitm k_mobilere k_opsec",m(F,null,"opsec")],
 ["t_secretscan","Secrets & code scanning","TruffleHog / gitleaks / apkleaks","Scanners for keys and tokens in repositories, JavaScript and app packages.","k_secrets k_jsanalysis",m(O,null,"process")],
 ["t_impersonate","Evasion & fingerprinting","curl_cffi / curl-impersonate","HTTP clients that reproduce real browsers' TLS and HTTP/2 fingerprints.","k_antibot",m(O,null,"collect")],
 ["t_stealth","Evasion & fingerprinting","Stealth automation browsers","Automation browsers patched to remove headless and automation tells (e.g. Camoufox, undetected-chromedriver).","k_antibot k_scraping",m(O,null,"collect")],
 ["t_hunchly","Capture & preservation","Hunchly","Browser extension that automatically captures, hashes and timestamps every page visited during an investigation.","k_capture",m(C,"https://www.hunch.ly","disseminate")],
 ["t_autoarchiver","Capture & preservation","Bellingcat Auto Archiver","Open-source pipeline that archives social-media posts and media listed in spreadsheets, with hashes and timestamps.","k_capture",m(O,"https://github.com/bellingcat/auto-archiver","disseminate")],
 ["t_archivebox","Capture & preservation","ArchiveBox / SingleFile","Self-hosted web archiving and single-file page capture.","k_capture k_archive",m(O,null,"disseminate")],
 ["t_misp","CTI platforms","MISP","Open-source threat-intelligence sharing platform with a large taxonomy ecosystem.","g_stix p_abusech",m(O,"https://www.misp-project.org","disseminate")],
 ["t_opencti","CTI platforms","OpenCTI","Open-source CTI knowledge platform structured on STIX 2.1 with ATT&CK mapping.","g_stix g_attack",m(O,"https://filigran.io","disseminate")],
 ["t_tor","OPSEC & environment","Tor Browser","Anonymity network client for accessing onion services and reducing attribution.","k_darkweb k_opsec",m(O,"https://www.torproject.org","opsec")],
 ["t_vm","OPSEC & environment","Hardened investigation VMs","Isolated, disposable environments (e.g. Trace Labs OSINT VM, CSI Linux, custom builds) separating investigator identity from targets.","k_opsec",m(O,null,"opsec")],
 ["t_vpn","OPSEC & environment","VPNs, proxies & managed attribution","Commercial VPNs, residential proxies and managed-attribution services controlling the investigator's apparent origin.","k_opsec k_sockpuppet",m(C,null,"opsec")],
 ["t_llm","AI & language","LLM assistants & agents","General-purpose LLMs and agents for summarizing, translating, extracting entities and drafting queries; results require source verification.","k_ai k_nlp",m(C,null,"process")],
 ["t_translate","AI & language","Machine translation","DeepL, Google Translate and similar for triaging foreign-language sources.","k_nlp",m(F,null,"process")],
 ["t_whisper","AI & language","Whisper & speech-to-text","Open-source automatic speech recognition for transcribing and translating audio and video.","k_nlp",m(O,"https://github.com/openai/whisper","process")]
],
discipline: [
 ["d_osint","Core","OSINT","Open-source intelligence: intelligence produced from publicly available information that is collected, exploited and disseminated to address a specific requirement.","d_socmint d_geoint d_cti d_finint d_darkint d_media d_adint s_web s_news s_gov"],
 ["d_socmint","Sub-discipline","SOCMINT","Social-media intelligence: collection and analysis of social-platform content and relationships.","s_social s_messaging s_forums s_video k_socialmon k_network"],
 ["d_geoint","Sub-discipline","GEOINT / IMINT","Geospatial and imagery intelligence from satellite, aerial and mapping data.","s_imagery s_maps s_sensor k_imint k_geoloc"],
 ["d_cti","Sub-discipline","Cyber threat intelligence (CTI)","Intelligence on adversaries, infrastructure and malware to inform defense.","s_threat s_scan s_domains s_certs s_darkweb s_code"],
 ["d_finint","Sub-discipline","FININT","Financial intelligence on ownership, transactions, trade and crypto-asset flows.","s_corp s_finance s_trade s_blockchain s_sanctions s_beneficial"],
 ["d_darkint","Sub-discipline","Underground / dark-web intelligence","Intelligence from criminal forums, markets, leak sites and breach data.","s_darkweb s_breach s_forums"],
 ["d_media","Sub-discipline","Media intelligence","Monitoring and analysis of news and broadcast media.","s_news s_video"],
 ["d_adint","Sub-discipline","ADINT / commercially available information","Intelligence derived from purchased commercial data such as ad-tech location data; under growing policy scrutiny.","s_mobile s_people k_adtech"],
 ["d_humint","Adjacent","HUMINT (adjacent)","Human-source intelligence; OSINT supplies leads, vetting and context, while sock-puppet engagement blurs the line.","k_sockpuppet"],
 ["d_sigint","Adjacent","SIGINT (adjacent)","Signals intelligence; open RF, ADS-B and AIS reception form its open-source edge.","s_rf s_adsb s_ais"],
 ["d_dfir","Adjacent","Digital forensics (adjacent)","Forensic examination of devices and files; shares metadata and preservation methods with OSINT.","k_metadata k_capture"]
],
usecase: [
 ["u_le","Public sector","Law enforcement & investigations","Suspect and network identification, fraud, child exploitation, organized crime and cybercrime investigations.","d_socmint d_finint d_darkint k_capture g_chain"],
 ["u_defense","Public sector","National security & defense","Situational awareness, order-of-battle tracking, early warning and counter-intelligence.","d_geoint d_sigint k_tracking g_ic"],
 ["u_journalism","Civil society & research","Investigative journalism & fact-checking","Verifying user-generated content, exposing networks and holding power to account.","k_verify k_geoloc d_media"],
 ["u_hr","Civil society & research","Human rights & accountability","Documenting atrocities and violations to standards usable by courts and UN mechanisms.","k_geoloc k_chrono k_capture g_berkeley d_geoint"],
 ["u_tns","Civil society & research","Trust & safety and disinformation research","Detecting coordinated inauthentic behavior, influence operations and platform abuse.","k_narrative k_network d_socmint g_disarm"],
 ["u_academic","Civil society & research","Academic & policy research","Computational social science, conflict studies and policy analysis built on open data.","k_scraping k_network g_dsa"],
 ["u_missing","Civil society & research","Missing persons & humanitarian response","Locating missing people and supporting disaster response with open data.","k_username d_socmint s_sensor"],
 ["u_cyber","Private sector","Cybersecurity & attack-surface management","Mapping exposed assets, tracking threat actors and detecting phishing infrastructure.","d_cti k_scan k_subdomain g_attack"],
 ["u_kyc","Private sector","Due diligence, KYC/AML & sanctions","Screening counterparties, uncovering beneficial owners and adverse media.","d_finint k_corp s_sanctions"],
 ["u_corpsec","Private sector","Corporate security & executive protection","Threat monitoring, travel security and exposure reduction for people and sites.","k_socialmon d_socmint s_people"],
 ["u_brand","Private sector","Brand protection & fraud","Detecting impersonation, counterfeit sites and scams.","k_socialmon k_tracker s_domains"],
 ["u_supply","Private sector","Supply-chain & ESG risk","Mapping suppliers, forced-labor exposure and export-control risk.","s_trade k_money k_corp"],
 ["u_redteam","Private sector","Red teaming & social-engineering assessments","Reconnaissance of staff, email formats and infrastructure for authorized testing.","k_email k_username k_subdomain g_attack"],
 ["u_litigation","Private sector","Litigation support & asset tracing","Locating assets, witnesses and evidence for disputes and judgment enforcement.","k_corp s_courts k_money"]
],
governance: [
 ["g_cycle","Process & analysis","Intelligence cycle","Planning & direction → collection → processing → analysis & production → dissemination → feedback; the backbone of OSINT workflows.","d_osint k_req",st("plan")],
 ["g_admiralty","Process & analysis","Admiralty / NATO source grading","Rates source reliability (A–F) and information credibility (1–6) independently.","k_sat k_report",st("analyze")],
 ["g_ach","Process & analysis","Analysis of Competing Hypotheses","Heuer's method of testing evidence against multiple hypotheses to counter confirmation bias.","k_sat",st("analyze")],
 ["g_attack","Standards & frameworks","MITRE ATT&CK","Adversary-behavior knowledge base; its Reconnaissance tactic (TA0043) describes adversaries' own OSINT on targets.","d_cti k_subdomain",st("plan")],
 ["g_stix","Standards & frameworks","STIX / TAXII","OASIS standards for representing and exchanging cyber threat intelligence.","d_cti",st("disseminate")],
 ["g_disarm","Standards & frameworks","DISARM framework","Open framework describing disinformation tactics, techniques and countermeasures.","k_narrative",st("analyze")],
 ["g_c2pa","Standards & frameworks","C2PA content credentials","Provenance standard that cryptographically binds origin and edit history to media files.","k_verify",st("analyze")],
 ["g_robots","Standards & frameworks","Robots Exclusion Protocol (RFC 9309)","robots.txt, standardized in 2022. Not access control, but ignoring it and crawling aggressively weakens legal and ethical standing.","k_scraping k_antibot",st("opsec")],
 ["g_owaspapi","Standards & frameworks","OWASP API Security Top 10","Taxonomy of API weaknesses; Broken Object Level Authorization ranks first in the 2023 edition. Useful for recognizing when collection has become exploitation.","k_apiexploit k_apienum",st("analyze")],
 ["g_mastg","Standards & frameworks","OWASP MASTG / MASVS","Mobile Application Security Testing Guide and verification standard; the reference methodology for app reversing, interception and pinning bypass.","k_mobilere k_mitm",st("plan")],
 ["g_berkeley","Ethics & evidence","Berkeley Protocol","UN OHCHR / UC Berkeley protocol on digital open-source investigations: legal, ethical and methodological standards for evidentiary work.","k_capture k_verify g_chain",st("plan")],
 ["g_chain","Ethics & evidence","Evidence standards & chain of custody","Hashing, metadata, documentation and reproducibility so open-source material is admissible; international courts including the ICC have relied on social-media video.","k_capture",st("disseminate")],
 ["g_ethics","Ethics & evidence","Ethics & harm minimization","Proportionality, necessity, bystander privacy, avoiding doxxing, and investigator wellbeing including vicarious trauma.","k_sockpuppet k_breach",st("opsec")],
 ["g_disclosure","Ethics & evidence","Coordinated vulnerability disclosure","When collection reveals an authorization flaw or exposed data, report it rather than harvest it; the US DOJ's 2022 CFAA charging policy declines to prosecute good-faith security research.","k_apiexploit k_secrets",st("opsec")],
 ["g_gdpr","Law & regulation","GDPR & data-protection law","Publicly available personal data is still personal data: lawful basis, minimization and retention apply (GDPR, UK GDPR, CCPA/CPRA and others).","s_people s_breach s_social k_scraping",st("opsec")],
 ["g_cfaa","Law & regulation","Computer-misuse law & platform terms","CFAA case law (Van Buren, hiQ v. LinkedIn, Meta and X v. Bright Data), the UK Computer Misuse Act and platform terms define limits on scraping and access. The key line is authorization: logged-out public data versus bypassing logins, technical barriers or other users' permissions.","k_scraping k_sockpuppet k_breach",st("opsec")],
 ["g_dmca","Law & regulation","Anti-circumvention & reverse-engineering law","DMCA §1201 in the US (with narrow security-research exemptions) and EU rules permitting software decompilation essentially only for interoperability govern bypassing protections and decompiling apps; EULAs add contractual bans.","k_mobilere k_mitm k_apireplay",st("opsec")],
 ["g_aiact","Law & regulation","EU AI Act","Among other restrictions, prohibits building facial-recognition databases through untargeted scraping of facial images.","k_reverseimg p_clearview p_pimeyes",st("opsec")],
 ["g_dsa","Law & regulation","EU Digital Services Act (Art. 40)","Creates vetted-researcher access to data from very large online platforms.","s_social p_metacl",st("opsec")],
 ["g_ic","Law & regulation","US IC OSINT Strategy & CAI policy","ODNI/CIA IC OSINT Strategy 2024–2026 and the 2024 policy framework for commercially available information.","d_osint d_adint",st("plan")]
],
community: [
 ["c_bellingcat","Investigative collectives","Bellingcat","Investigative collective that popularized open-source methods; publishes guides and an online investigations toolkit.","k_geoloc k_verify t_autoarchiver u_journalism",m(null,"https://www.bellingcat.com")],
 ["c_dfrlab","Investigative collectives","Atlantic Council DFRLab","Digital Forensic Research Lab studying disinformation and influence operations.","k_narrative u_tns",m(null,"https://dfrlab.org")],
 ["c_cir","Investigative collectives","Centre for Information Resilience","Open-source investigations into conflict and human-rights abuses (e.g. Eyes on Russia).","u_hr k_geoloc",m(null,"https://www.info-res.org")],
 ["c_hrc","Investigative collectives","UC Berkeley Human Rights Center","Investigations Lab training students in open-source methods; co-author of the Berkeley Protocol.","g_berkeley u_hr",m()],
 ["c_tracelabs","Practice & challenges","Trace Labs","Nonprofit running Search Party CTFs that crowdsource OSINT on missing-persons cases.","u_missing t_vm",m(null,"https://www.tracelabs.org")],
 ["c_quiztime","Practice & challenges","Quiztime & geolocation challenges","Community puzzles (and games like GeoGuessr) that build geolocation and chronolocation skills.","k_geoloc k_chrono",m()],
 ["c_sans","Training & certification","SANS SEC487 / GOSI","Commercial OSINT course with the GIAC Open Source Intelligence certification.","d_osint",m(null,"https://www.sans.org")],
 ["c_inteltechniques","Training & certification","IntelTechniques","Michael Bazzell's books and training on OSINT techniques and investigator privacy.","k_opsec k_dorking",m(null,"https://inteltechniques.com")],
 ["c_osintfoundation","Training & certification","OSINT Foundation","Professional association for OSINT practitioners in the US intelligence community.","g_ic",m()],
 ["c_osintcurious","Directories & resources","OSINT Curious","Community project publishing free OSINT webcasts, articles and tips.","d_osint",m()],
 ["c_gijn","Directories & resources","GIJN","Global Investigative Journalism Network: guides, tipsheets and research resources for reporters.","u_journalism",m(null,"https://gijn.org")],
 ["c_osintframework","Directories & resources","OSINT Framework","Interactive directory of free OSINT resources organized by category.","d_osint",m(null,"https://osintframework.com")],
 ["c_awesome","Directories & resources","Awesome-OSINT & tool lists","Community-maintained tool lists on GitHub plus Bellingcat's online investigations toolkit.","d_osint c_bellingcat",m(null,"https://github.com/jivoi/awesome-osint")]
],
trend: [
 ["r_api","Access","Platform API lockdowns","X API paywalls and Reddit API pricing (2023) and CrowdTangle's 2024 shutdown pushed researchers to scraping, paid vendors and regulated access programs.","s_social p_xapi p_metacl k_scraping g_dsa"],
 ["r_whois","Access","WHOIS redaction & RDAP","Post-GDPR redaction removed most registrant data; ICANN replaced WHOIS with RDAP as the required gTLD lookup protocol on 28 January 2025.","s_domains k_pdns"],
 ["r_encrypted","Access","Shift to closed & ephemeral spaces","Activity migrating to Telegram, Discord, private groups and disappearing messages shrinks the open surface.","s_messaging k_sockpuppet"],
 ["r_linkrot","Access","Content takedowns & link rot","Moderation and deletion erase potential evidence, making rapid preservation essential.","k_capture s_archives"],
 ["r_antibot","Access","Anti-bot & fingerprinting arms race","Cloudflare, Akamai, DataDome, HUMAN and others score TLS, browser and behavioral fingerprints and increasingly block automated and AI crawlers by default, raising collection cost.","k_antibot p_brightdata k_scraping"],
 ["r_attest","Access","Hardened mobile clients","Certificate pinning, obfuscation, request signing and device attestation (Play Integrity, App Attest) make private APIs harder to call outside the genuine app.","k_mobilere k_apireplay k_mitm"],
 ["r_loginwall","Access","Login walls & logged-out restrictions","Platforms increasingly gate content behind accounts, pushing collection toward authenticated sessions where terms-of-service and unauthorized-access arguments are stronger.","s_social k_privateclients g_cfaa k_sockpuppet"],
 ["r_genai","Technology","Generative AI & synthetic media","Deepfakes, synthetic personas and AI content farms raise the verification burden.","k_verify g_c2pa"],
 ["r_llm","Technology","AI-augmented OSINT","LLM agents for collection, translation and triage increase scale but introduce hallucination and provenance risk.","t_llm k_ai"],
 ["r_space","Technology","Commercial space proliferation","More optical and SAR satellites with faster revisit make near-real-time imagery widely accessible.","s_imagery p_planet p_sar"],
 ["r_stealer","Operating environment","Infostealer-log economy","Mass-scale stealer logs expose credentials and session cookies: powerful but ethically fraught data.","s_breach p_spycloud p_flare"],
 ["r_gnss","Operating environment","GNSS jamming & transponder spoofing","Widespread GPS interference and AIS/ADS-B spoofing degrade tracking-data reliability.","s_ais s_adsb k_tracking"],
 ["r_conflict","Operating environment","Conflict OSINT at scale","Wars in Ukraine, Gaza, Sudan and elsewhere drove crowd-sourced verification alongside information overload and manipulation.","k_geoloc u_hr r_genai"],
 ["r_privacy","Regulation","Privacy & data-broker regulation","Tighter data-protection enforcement and US federal and state data-broker rules limit people-data availability.","s_people g_gdpr k_adtech"],
 ["r_gov","Regulation","Institutionalization of OSINT","Governments formalize OSINT as a discipline while debating the purchase of commercially available data.","g_ic d_adint"]
]
};
